version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db

  backend:
    image: ${DOCKERHUB_USERNAME}/mean-backend:latest
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASS}@mongo:27017/${MONGO_DB}?authSource=admin"

  frontend:
    image: ${DOCKERHUB_USERNAME}/mean-frontend:latest
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mongo_data:

